# Generated by Django 4.2.10 on 2024-03-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='class_interested',
            field=models.CharField(blank=True, choices=[('Mat Pilates for Stabilization', 'Mat Pilates for Stabilization'), ('Mat Pilates Flow', 'Mat Pilates Flow'), ('Strength and Stretch Movement Class', 'Strength and Stretch Movement Class')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DropdownObject',
        ),
    ]
