# Generated by Django 4.2.10 on 2024-03-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_booking', '0003_alter_booking_member'),
        ('member', '0002_userprofile_remove_memberlogin_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberLogin',
        ),
    ]
