# Generated by Django 4.2.10 on 2024-03-03 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(choices=[('Mat Pilates for Stabilization', 'Mat Pilates for Stabilization'), ('Mat Pilates Flow', 'Mat Pilates Flow'), ('Strength and Stretch Movement Class', 'Strength and Stretch Movement Class')], max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(choices=[('Mat Pilates for Stabilization', '30 minutes'), ('Mat Pilates Flow', '45 minutes'), ('Strength and Stretch Movement Class', '60 minutes')], max_length=50)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
                ('booked_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_booking.class')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
