# Generated by Django 4.2.10 on 2024-03-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassDetails',
        ),
    ]
