# Generated by Django 4.2.10 on 2024-03-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userprofile_remove_memberlogin_member'),
        ('class_booking', '0002_rename_class_classdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.userprofile'),
        ),
    ]
