# Generated by Django 4.2.10 on 2024-03-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_booking', '0003_alter_booking_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassDetails',
            new_name='ClassDetail',
        ),
    ]
